service: serverlessSetup

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1

functions:
  nft-sig:
    handler: src/functions/nft-sig.handler
    events:
      - http:
          path: serverlessSetup/nft-sig
          method: post

plugins:
  - serverless-plugin-typescript
  - serverless-offline
